#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

struct _enum_TExtArgumentType
  Int8::Int32
  Int16::Int32
  Int32::Int32
  Int64::Int32
  Float::Int32
  Double::Int32
  Void::Int32
  PInt8::Int32
  PInt16::Int32
  PInt32::Int32
  PInt64::Int32
  PFloat::Int32
  PDouble::Int32
  Bool::Int32
  ArrayInt8::Int32
  ArrayInt16::Int32
  ArrayInt32::Int32
  ArrayInt64::Int32
  ArrayFloat::Int32
  ArrayDouble::Int32
  GeoPoint::Int32
  Cursor::Int32
end
const TExtArgumentType = _enum_TExtArgumentType(Int32(0), Int32(1), Int32(2), Int32(3), Int32(4), Int32(5), Int32(6), Int32(7), Int32(8), Int32(9), Int32(10), Int32(11), Int32(12), Int32(13), Int32(14), Int32(15), Int32(16), Int32(17), Int32(18), Int32(19), Int32(20), Int32(21))

struct _enum_TOutputBufferSizeType
  kUserSpecifiedConstantParameter::Int32
  kUserSpecifiedRowMultiplier::Int32
  kConstant::Int32
end
const TOutputBufferSizeType = _enum_TOutputBufferSizeType(Int32(0), Int32(1), Int32(2))


mutable struct TUserDefinedFunction <: Thrift.TMsg
  name::String
  argTypes::Vector{Int32}
  retType::Int32
  TUserDefinedFunction() = (o=new(); fillunset(o); o)
end # mutable struct TUserDefinedFunction

mutable struct TUserDefinedTableFunction <: Thrift.TMsg
  name::String
  sizerType::Int32
  sizerArgPos::Int32
  inputArgTypes::Vector{Int32}
  outputArgTypes::Vector{Int32}
  sqlArgTypes::Vector{Int32}
  TUserDefinedTableFunction() = (o=new(); fillunset(o); o)
end # mutable struct TUserDefinedTableFunction
