#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


module completion_hints

using Thrift
import Thrift.process, Thrift.meta, Thrift.distribute




export meta
export TCompletionHintType # enum
export TCompletionHint # struct

include("completion_hints_constants.jl")
include("completion_hints_types.jl")
include("completion_hints_impl.jl")  # server methods to be hand coded


end # module completion_hints
