#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

struct _enum_TCompletionHintType
  COLUMN::Int32
  TABLE::Int32
  VIEW::Int32
  SCHEMA::Int32
  CATALOG::Int32
  REPOSITORY::Int32
  FUNCTION::Int32
  KEYWORD::Int32
end
const TCompletionHintType = _enum_TCompletionHintType(Int32(0), Int32(1), Int32(2), Int32(3), Int32(4), Int32(5), Int32(6), Int32(7))


mutable struct TCompletionHint <: Thrift.TMsg
  _type::Int32
  hints::Vector{String}
  replaced::String
  TCompletionHint() = (o=new(); fillunset(o); o)
end # mutable struct TCompletionHint
