/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef completion_hints_CONSTANTS_H
#define completion_hints_CONSTANTS_H

#include "completion_hints_types.h"



class completion_hintsConstants {
 public:
  completion_hintsConstants();

};

extern const completion_hintsConstants g_completion_hints_constants;



#endif
