/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mapd_CONSTANTS_H
#define mapd_CONSTANTS_H

#include "mapd_types.h"



class mapdConstants {
 public:
  mapdConstants();

};

extern const mapdConstants g_mapd_constants;



#endif
