#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


module common

using Thrift
import Thrift.process, Thrift.meta, Thrift.distribute




export meta
export TDeviceType # enum
export TDatumType # enum
export TEncodingType # enum
export TTypeInfo # struct

include("common_constants.jl")
include("common_types.jl")
include("common_impl.jl")  # server methods to be hand coded


end # module common
